Fix traceback on seek with two mouse buttons
Two mouse button down events in rapid succession can cause

Traceback (most recent call last):
  File "/usr/share/sugar/activities/Record.activity/record.py", line 662, in _button_press
    self.model.seek_start()
  File "/usr/share/sugar/activities/Record.activity/model.py", line 351, in seek_start
    self.gplay.pause()
  File "/usr/share/sugar/activities/Record.activity/gplay.py", line 126, in pause
    GObject.source_remove(self._playback_monitor_handler)
TypeError: Argument 0 does not allow None as a value

Check the handler is scheduled before trying to remove it.