Fix camera detection on Fedora 28
On Fedora 28, switch camera button is available with only one camera,
and gives traceback on second click;

Traceback (most recent call last):
  File "record.py", line 349, in __switch_camera_click_cb
    self.model.switch_camera()
  File "model.py", line 108, in switch_camera
    self.glive.switch_camera()
  File "glive.py", line 68, in switch_camera
    self._camera = eyes[(eyes.index(self._camera)) + 1 % len(eyes)]
IndexError: list index out of range

Turns out with kernel 4.16, each camera is presented as two devices
in /dev/video* or /dev/v4l/by-id/*, so filter for *index0 only.

Also, the limiting of the index was wrong, parentheses needed.

Reported-by: Walter Bender <walter.bender@gmail.com>